import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { signIn } from "next-auth/react";
import LoginButton from "@/components/button/LoginButton";
import Navbar from "@/components/layout/Navbar";
import { Providers } from "./Providers";
import SessionGuard from "@/components/SessionGuard";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
		<Providers>
			<Navbar title={metadata.title}/>

			{children}
		</Providers>

      </body>
    </html>
  );
}
